# Site settings
title: 阿川的个人博客
email: achuan@achuan.io
description: > #阿川的个人博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://achuan.io/index.html" # the base hostname & protocol for your site

# Paginate（分页）
#gems: [jekyll-paginate]
# 分页时每页博文数量
#paginate: 10
#paginate_path: "page:num"


# Build settings
# 语法高亮
highlighter: rouge
# markdown解释器
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

#relative_permalinks:true
#博文的链接样式
permalink: /:year-:month-:day-:title.html

favicon: /assets/image/favicon.ico

# 博客作者相关
author:
  name: Hong-hai zhang
  email: achuan@achuan.io
  link: https://achuan.io
  Qzone: https://user.qzone.qq.com/2434929041
  github: https://github.com/achuanya
  github_username: achuanya
  github_repositories: https://github.com/achuanya/achuanya.github.io
  github_subscription: https://github.com/achuanya/achuanya.github.io/subscription


locals:
  tags: 标签
  about: 关于
  active: 技术
subscribe_rss: /pages/atom.xml

# 头像
avatar: /assets/image/avatar.jpg

# 网站CSS路径
css: /assets/css/

# 网站JS路径
js: /assets/js/

# 网站图片路径
image: /assets/image/

# Rss
name: 阿川的个人博客
description: 执着于理想，纯粹于当下
url: https://achuan.io

# Disqus设置
disqus: 
id: 阿川